#############  Animations settings  ##############
source=./Animations.conf              
##################################################

##################  Keybinds  ####################
source=./Keybinds.conf
##################################################

#############  Monitors settings  ################
source=./Monitors.conf
##################################################

##############  General settings  ################
source=./General.conf
##################################################

##############  Autostart on boot  ###############
source=./Autostart.conf
##################################################

################ Blur settings  ##################
source=./Blur.conf
##################################################

##############  Scroller settings  ###############
source=./Scroller_layout.conf
##################################################

############  Window n Layer rules  ##############
source=./Rules.conf
##################################################

###########  Environment variables  ##############
source=./Environments.conf
##################################################

##################  Tagrules  ####################
source=./Tagrules.conf
##################################################

################  Master-Stack  ##################
source=./Master-Stack.conf
##################################################

##################  Shadows  #####################
source=./Shadows.conf
##################################################
